[package]
name = "payego-seeder"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
diesel = { workspace = true }
payego-primitives = { workspace = true }
uuid = { workspace = true }
secrecy = { workspace = true }
argon2 = { workspace = true }
dotenvy = { workspace = true }
rand = { workspace = true }
